### DISCUSSION TITLE
Help using wud.tag.transform

### DISCUSSION THREAD

**Discussion by Noneangel** [getwud/wud#576] [Q&A]
I try to monitor the [rtuszik/photon-docker](https://github.com/rtuszik/photon-docker) images.
The tags don't quiet follow the semver format:
>  I wanted to peg my version numbers to the photon release versions, which is why I initially just took used that directly. This however wouldn't allow me to release updated versions of my image on GitHub, which is why I opted for the custom scripting which allows me to add revision suffixes to the version.

[from this post.](https://github.com/rtuszik/photon-docker/issues/7#issuecomment-2396915349)

List of some tags (newest to oldest):
- 0.6.2-rev.1
- 0.6.2

My setup:
```
services:
  photon:
    image: rtuszik/photon-docker:0.6.2-rev.1
    labels:
      - 'wud.watch=true'
      - 'wud.tag.include=^\d+\.\d+\.\d+(-rev\.\d+)?$$'
```
Problem: `0.6.2` is considered an update over `0.6.2-rev.1`.
