### DISCUSSION TITLE
[Quay.io] Wrong latest tag for image

### DISCUSSION THREAD

**Discussion by Chucky2401** [getwud/wud#588] [Q&A]
Hello,

I experience a little issue with WUD, only with an image on Quay.io, I think this is cause by the tag format.

It is for the image *inv-sig-helper* from **[Invidious](https://quay.io/repository/invidious/inv-sig-helper?tab=tags&tag=latest)**.

In WUD, it shows me to upgrade from **master-614e2e2** to **master-52097ac**

![Image](https://github.com/user-attachments/assets/f3c767bb-637b-4d0e-bb7b-1446358b12a3)

But from the repository I already set the latest tag

![Image](https://github.com/user-attachments/assets/9480b4a0-63e3-4de2-b433-b65fbd9fc81c)

Is there something I can do to avoid that? I look in the documentation to the label `wud.tag.transform`, but I'm not sure what to write.

Here my compose.yml file

```yaml
services:
  invidious:
    image: quay.io/invidious/invidious:2025.01.22-8ee73aa
    container_name: invidious
    restart: always
    ports:
      - 3000:3000
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: redacted
          password: redacted
          host: invidious-db
          port: 5432
        check_tables: true
        signature_server: inv_sig_helper:12999
        visitor_data: redacted
        po_token: redacted
        hmac_key: "redacted"
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/trending || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
    logging:
      options:
        max-size: "1G"
        max-file: "4"
    depends_on:
      - invidious-db
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+-[a-f0-9]+$$

  inv_sig_helper:
    image: quay.io/invidious/inv-sig-helper:master-614e2e2
    container_name: invidious-sig-helper
    init: true
    command: ["--tcp", "0.0.0.0:12999"]
    environment:
      - RUST_LOG=info
    restart: always
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true

  invidious-db:
    image: docker.io/library/postgres:14
    container_name: invidious-db
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./config/sql:/config/sql
      - ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: redacted
      POSTGRES_PASSWORD: redacted
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
    labels:
      - wud.watch=false

volumes:
  postgresdata:
```
