### DISCUSSION TITLE
Force upgrading minor versions only

### DISCUSSION THREAD

**Discussion by mbnoimi** [getwud/wud#589] [Q&A] [answered]
I don't want to upgrade PostgreSQL to major versions so I used `wud.tag.include=^17\\.[0-9]+\\.[0-9]+$` but it seems invalid format.

What's wrong in my code?

```yml

services:
  postgresql:
    container_name: "cloud-postgresql"
    image: postgres
    volumes:
      - /home/Storage/Config/Postgresql/data:/var/lib/postgresql/data
      - /home/Storage/Config/Postgresql/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=0
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --lc-collate=C --lc-ctype=C
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 30s
      timeout: 10s
      retries: 5
    labels: # --------> Look here please
      - wud.watch=false
      - wud.tag.include=^17\.[0-9]+\.[0-9]+$
      
  wud:
    container_name: "cloud-wud"
    image: getwud/wud
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    environment:
      - WUD_TRIGGER_DOCKER_LOCAL_PRUNE=true
      - WUD_TRIGGER_DOCKER_LOCAL_DRYRUN=false
```
