### DISCUSSION TITLE
Please help! Trigger executed with error – ''Cannot destructure property 'dockerApi' of 'watcher' as it is undefined''

### DISCUSSION THREAD

**Discussion by mxlb-dev** [getwud/wud#609] [Q&A]
Hi, I am new to WUD and get most of it working: All containers incl. pending updates get displayed properly in UI, notification triggers, OIDC auth, private registries... all works fine. However, I struggle to implement automatic updates.

Testing the docker trigger – which I am assuming should do the update – outputs:
> Trigger executed with error (Error when running trigger docker.pve02 (Cannot destructure property 'dockerApi' of 'watcher' as it is undefined.)})

Could you please advise on what's wrong? 🙏  

Many thanks! 🫠

Details:

**WUD compose file:**
```
whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - wud-store:/store
    networks:
      stack_net:
      macvlan_net:
        ipv4_address: 10.12.22.85
    ports:
      - 3000:3000
    env_file:
      - .env
    labels:
      # WHATSUPDOCKER
      - wud.watch=true
      - wud.display.name=WhatsUpDocker
      # - wud.display.icon=si:uptimekuma
      # ENABLE NOTIFICATIONS
      - wud.trigger.include=smtp.discord 
      # DISABLE AUTO-UPDATE AND PRUNE
      - wud.trigger.exclude=docker.pve02
```

**WUD env file:**
```
# WUD PVE02 DOCKER HOST
# My local docker host
WUD_WATCHER_pve02_SOCKET=/var/run/docker.sock
# Trigger that should ideally update and prune (but not working)
WUD_TRIGGER_DOCKER_pve02_PRUNE=true
```

**Within stacks I use labels for each container, example:**
```
services:
  myservice:
    image: my/service:latest
    restart: unless-stopped
    container_name: myservice
    env_file:
      - .env
    labels:
      # WHATSUPDOCKER
      - wud.watch=true
      - wud.display.name=My Service
      - wud.display.icon=mdi:icon
      # ENABLE NOTIFICATIONS
      - wud.trigger.include=smtp.discord 
      # AUTO-UPDATE AND PRUNE ON ALL RELEASES (not working, I tested also :minor and :patch)
      - wud.trigger.include=docker.pve02:major
```

Log is on debug level and looks fine (at least to me):

```
wud  | 13:15:22.484  INFO whats-up-docker: WUD is starting (version = 8.0.1)
wud  | 13:15:22.487  INFO whats-up-docker/store: Load store from (/store/wud.json)
wud  | 13:15:22.514  INFO whats-up-docker/prometheus: Init Prometheus module
wud  | 13:15:22.521 DEBUG whats-up-docker: Start container metrics interval
wud  | 13:15:22.563  INFO whats-up-docker/registry: Register all components of kind trigger for provider smtp
wud  | 13:15:22.606  INFO whats-up-docker/trigger.smtp.mail: Register with configuration {"user":"m072658c","host":"w00baab3.kasserver.com","from":"system@mxlb.net","pass":"u******************o","simpletitle":"Container ${container.name} can be updated","tls":{"enabled":true,"verify":true},"to":"maks3k@gmail.com","port":587,"auto":true,"threshold":"all","mode":"simple","once":true,"simplebody":"Container ${container.name} running with ${container.updateKind.kind} ${container.updateKind.localValue} can be updated to ${container.updateKind.kind} ${container.updateKind.remoteValue}${container.result && container.result.link ? \"\\n\" + container.result.link : \"\"}","batchtitle":"${containers.length} updates available"}
wud  | 13:15:22.614  INFO whats-up-docker/registry: Register all components of kind trigger for provider discord
wud  | 13:15:22.820  INFO whats-up-docker/trigger.discord.schwiftyland: Register with configuration {"url":"h***********************************************************************************************************************I","botusername":"WhatsUpDocker","cardcolor":65280,"cardlabel":"","auto":true,"threshold":"all","mode":"simple","once":true,"simpletitle":"New ${container.updateKind.kind} found for container ${container.name}","simplebody":"Container ${container.name} running with ${container.updateKind.kind} ${container.updateKind.localValue} can be updated to ${container.updateKind.kind} ${container.updateKind.remoteValue}${container.result && container.result.link ? \"\\n\" + container.result.link : \"\"}","batchtitle":"${containers.length} updates available"}
wud  | 13:15:22.820  INFO whats-up-docker/registry: Register all components of kind trigger for provider docker
wud  | 13:15:23.251  INFO whats-up-docker/trigger.docker.pve02: Register with configuration {"prune":true,"dryrun":false,"auto":true,"threshold":"all","mode":"simple","once":true,"simpletitle":"New ${container.updateKind.kind} found for container ${container.name}","simplebody":"Container ${container.name} running with ${container.updateKind.kind} ${container.updateKind.localValue} can be updated to ${container.updateKind.kind} ${container.updateKind.remoteValue}${container.result && container.result.link ? \"\\n\" + container.result.link : \"\"}","batchtitle":"${containers.length} updates available"}
wud  | 13:15:23.251  INFO whats-up-docker/trigger.smtp.mail: Registering for auto execution
wud  | 13:15:23.251  INFO whats-up-docker/trigger.discord.schwiftyland: Registering for auto execution
wud  | 13:15:23.252  INFO whats-up-docker/trigger.docker.pve02: Registering for auto execution
wud  | 13:15:23.253  INFO whats-up-docker/registry: Register all components of kind registry for provider ecr
wud  | 13:15:23.384  INFO whats-up-docker/registry.ecr.public: Register with configuration {}
wud  | 13:15:23.385  INFO whats-up-docker/registry: Register all components of kind registry for provider gcr
wud  | 13:15:23.389  INFO whats-up-docker/registry.gcr.public: Register with configuration {}
wud  | 13:15:23.389  INFO whats-up-docker/registry: Register all components of kind registry for provider ghcr
wud  | 13:15:23.390  INFO whats-up-docker/registry.ghcr.public: Register with configuration {}
wud  | 13:15:23.390  INFO whats-up-docker/registry: Register all components of kind registry for provider hub
wud  | 13:15:23.393  INFO whats-up-docker/registry.hub.public: Register with configuration {"password":"d**********************************A","login":"dockerblau"}
wud  | 13:15:23.393  INFO whats-up-docker/registry: Register all components of kind registry for provider quay
wud  | 13:15:23.399  INFO whats-up-docker/registry.quay.public: Register with configuration {}
wud  | 13:15:23.399  INFO whats-up-docker/registry: Register all components of kind registry for provider lscr
wud  | 13:15:23.401  INFO whats-up-docker/registry.lscr.linuxserverio: Register with configuration {"token":"g**************************************g","username":"https://docker.getoutline.com"}
wud  | 13:15:23.402  INFO whats-up-docker/registry: Register all components of kind registry for provider custom
wud  | 13:15:23.432  INFO whats-up-docker/registry.custom.outline: Register with configuration {"url":"https://docker.getoutline.com"}
wud  | 13:15:23.601  INFO whats-up-docker/watcher.docker.pve02: Register with configuration {"socket":"/var/run/docker.sock","port":2375,"cron":"0 * * * *","watchbydefault":true,"watchall":false,"watchevents":true,"watchatstart":true}
wud  | 13:15:23.604  INFO whats-up-docker/watcher.docker.pve02: Cron scheduled (0 * * * *)
wud  | 13:15:23.634  INFO whats-up-docker/registry: Register all components of kind authentication for provider oidc
wud  | (node:7) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
wud  | (Use `node --trace-deprecation ...` to show where the warning was created)
wud  | 13:15:24.633  INFO whats-up-docker/watcher.docker.pve02: Listening to docker events
wud  | 13:15:24.700 DEBUG whats-up-docker/api: API/UI enabled => Start Http listener on port 3000
wud  | 13:15:24.709  INFO whats-up-docker/api: Server listening on port 3000 (HTTP)
```

**Comment by mxlb-dev** [comment]
Not sure if related: I just noticed, that old hosts, which I had once included, but not anymore are still showing their containers in WUD UI. Is there a way to clean the WUD db/storage?

**Comment by mxlb-dev** [comment]
ping

**Comment by Owl-Tec** [comment]
Did you ever figure this problem out? I currently have the same issue.

**Comment by kccorl1993** [comment]
Also running into this. I am simply trying to get my containers to update and nothing else special.

Here's my compose:

```
services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    environment:
      - TZ=America/New_York
      # Auth
      - WUD_AUTH_BASIC_LOCAL_USER=${BASIC_USER}
      - WUD_AUTH_BASIC_LOCAL_HASH=${BASIC_USER_HASH}
      # Registries
      - WUD_REGISTRY_LSCR_PRIVATE_USERNAME=${GITHUB_USER}
      - WUD_REGISTRY_LSCR_PRIVATE_TOKEN=${GITHUB_TOKEN}
      # Triggers
      - WUD_TRIGGER_DOCKER_LOCAL_PRUNE=true
      - WUD_TRIGGER_DOCKER_LOCAL_MODE=batch
      - WUD_TRIGGER_DOCKER_LOCAL_SIMPLETITLE=Container $${container.name} can be updated
      - WUD_TRIGGER_DOCKER_LOCAL_SIMPLEBODY=Container $${name} can be updated from $${local.substring(0, 15)} to $${remote.substring(0, 15)}
      # Watcher
      - WUD_WATCHER_LOCAL_CRON=0 5 * * *
      - WUD_WATCHER_LOCAL_SOCKET=/var/run/docker.sock
      # Notifications
      - WUD_TRIGGER_DISCORD_LOCAL_SIMPLETITLE=Container $${container.name} can be updated
      - WUD_TRIGGER_DISCORD_LOCAL_SIMPLEBODY=Container $${name} can be updated from $${local.substring(0, 15)} to $${remote.substring(0, 15)}
      - WUD_TRIGGER_DISCORD_LOCAL_URL=${DISCORD_NOTIFICATION_WEBHOOK}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/appdata/wud:/store
    ports:
      - 3000:3000
```
