### DISCUSSION TITLE
Codeberg registry or watcher configuration

### DISCUSSION THREAD

**Discussion by viharm** [getwud/wud#656] [Q&A] [answered]
I have seen a couple of discussions about watching images hosted at _Codeberg_'s container registry. _Forgejo_ is the most common & that is what I'm also using.

However I keep failing to configure the watcher for _Forgejo_ hosted at _Codeberg_ container registry.

I've tried setting up a _Codeberg_ token and passed it as an environment variable to the WUD container to setup  _Codeberg_ as a registry.

```yaml
WUD_REGISTRY_FORGEJO_CODEBERG_URL: "https://codeberg.org"
WUD_REGISTRY_FORGEJO_CODEBERG_LOGIN: "username"
WUD_REGISTRY_FORGEJO_CODEBERG_PASSWORD__FILE: "/path/to/WUD_REGISTRY_FORGEJO_CODEBERG_PASSWORD.file"
```

During _WUD_ container startup, a message shows up as registering a forgejo registry

```
INFO whats-up-docker/registry: Register all components of kind registry for provider forgejo
INFO whats-up-docker/registry.forgejo.codeberg: Register with configuration {"login":"username","url":"https://codeberg.org","password":"d**************************************e"}
```
But the _Forgejo_ container still shows `unknown registry`.

![image](https://github.com/user-attachments/assets/2efff3f0-3c9e-4105-a711-f001fda4642d)

Has anyone been able to successfully configure the registry and the container labels for _Codeberg_/ _Forgejo_?
