### DISCUSSION TITLE
How to auto update my containers

### DISCUSSION THREAD

**Discussion by varazir** [getwud/wud#697] [General]
Hello, 

I'm using Dockge to setup my containers. 
It's shown in the web GUI that there is a new version but no triggers. 
What is it I'm doing wrong? 

This is the compos for Dockge and WUD ( separate files ) 
```
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data

      # If you want to use private registries, you need to share the auth file with Dockge:
      # - /root/.docker/:/root/.docker

      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /opt/stacks:/opt/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/opt/stacks
      - WUD_TRIGGER_DOCKER_DOCKGE_DRYRUN=False
      - WUD_TRIGGER_DOCKER_DOCKGE_PRUNE=False
    labels:
      - "wud.watch=true"
      - "wud.trigger.docker.update=true"


services:
  wud:
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pi/wud-data:/data
    ports:
      - 3001:3000
    image: getwud/wud
    environment:
      # (Required) Check for new images every night at 3:00 AM
      - WUD_WATCHER_DOCKER_LOCAL_CRON=0 3 * * *
      # (Recommended) Set your timezone for accurate cron scheduling
      - TZ=Europe/Stockholm
      # (Optional) Other useful settings
      - WUD_LOG_LEVEL=info
      - WUD_TRIGGER_DOCKER_WATCH_STOPPED=false # Don't try to update stopped containers
    labels:
      # (Required) Tell WUD to watch and update itself!
      - wud.watch=true
      - wud.trigger.docker.update=true
networks:
  pi_default:
    external: true
volumes:
  wud-data: null

```
