### ISSUE TITLE
 Error when creating container grafana ((HTTP code 400) unexpected - Container cannot be connected to network endpoints: dlbox_private, backend_private ) (container=local_grafana)

### ISSUE THREAD

**Issue by r0m1CH** [getwud/wud#169]
Hello,

I encounter a new issue with automatic updates through my docker-compose file.
I have a grafana container which needs to be updated. WUD sees the update, download it, stop my container and try to recreate the new one.

However it will never get back online. Here the log, I have:
 _Error when creating container grafana ((HTTP code 400) unexpected - Container cannot be connected to network endpoints: dlbox_private, backend_private ) (container=local_grafana)_

Anything am I doing wrong here or any configuration i'm missing ?

Thanks for your help.

**Comment by r0m1CH** [comment]
Anything ? i do see that docker does not accept to be connect to both network directly at the beginning.
It seems that docker needs to connect the container to only one network at the start, then disconnect from it and finally connect, to both networks.
Does that make sense for you ?

**Comment by Teleportist** [comment]
Could this be anything to do with Grafana using the same port as What's Up Docker for it's webui?
If so, maybe port mapping WUD to another port on the host (eg. 3333:3000) would fix it?

**Comment by r0m1CH** [comment]
I can try but the error seems to be specific to the multiple network instead no? I have this issue with all my container that use 2 or more networks.
I find a similar case on Watchtower's project and seems to solved it the way i describe it into the second post:
_It seems that docker needs to connect the container to only one network at the start, then disconnect from it and finally connect, to both networks._

**Comment by fmartinou** [comment]
Hi,

Can you provide your docker-compose file, please (so that I can make some tests on my end)?

**Comment by r0m1CH** [comment]
Hi, 

Here you go : https://pastebin.com/5HAchU0T
This is teslamate project.
In this example, my PostgreSQL database is only available in an isolated backend network when the rest is on the LAN.

**Comment by Zatow** [comment]
Hi,

I have a same issue with all container using 2 networks : `Error when creating container APPS_Uptime-Kuma ((HTTP code 400) unexpected - Container cannot be connected to network endpoints: APPS, TRAEFIK ) (container=local_APPS_Uptime-Kuma)`

When I comment out the APPS or TRAEFIK network of my APPS_Uptime-Kuma container, I don't get an error.

My compose :
```
version: '3.9'

services:
  APPS_Uptime-Kuma:
    container_name: APPS_Uptime-Kuma
    image: louislam/uptime-kuma:1.20.1
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Pour que uptime-kuma puisse écouter les événements Docker
      - ./${SERVICE_UPTIME_KUMA}/data:/app/data
    environment:
      - TZ=${TZ}
    networks:
      - TRAEFIK
      - APPS
    labels:
      - wud.watch=true
      - wud.watch.digest=false
      - wud.tag.include=^\d+\.\d+\.\d+$$
  APPS_WUD:
    image: fmartinou/whats-up-docker:6.0.2
    container_name: APPS_WUD
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker-compose.yaml:/wud/docker-compose.yaml
    ports:
      - 3000:3000
    networks:
      - TRAEFIK
      - APPS
    restart: unless-stopped
    environment:
      - WUD_WATCHER_LOCAL_CRON=0 * * * *
      - WUD_WATCHER_LOCAL_WATCHBYDEFAULT=false
      - WUD_REGISTRY_HUB_LOGIN=login
      - WUD_REGISTRY_HUB_PASSWORD=password
      - WUD_TRIGGER_DOCKERCOMPOSE_APPS_MODE=batch
      - WUD_TRIGGER_DOCKERCOMPOSE_APPS_FILE=/wud/docker-compose.yaml
      - WUD_TRIGGER_DOCKERCOMPOSE_APPS_BACKUP=false
      - WUD_TRIGGER_DOCKERCOMPOSE_APPS_PRUNE=false
    labels:
    #### WUD ####
      - wud.watch=true
      - wud.watch.digest=false
      - wud.tag.include=^\d+\.\d+\.\d+$$
networks:
  TRAEFIK:
    external: true
  APPS:
    external: true
```
