### ISSUE TITLE
Watcher incorrect username or password

### ISSUE THREAD

**Issue by zsamiatt** [getwud/wud#182]
Hello!

I using latest WUD on RPi and Synology NAS. Lately since no updates are coming I looked through the logs.

I have error:

07:37:18.305  WARN whats-up-docker/watcher.docker.local: Error when processing (401 - {"details":"incorrect username or password"}) (container=local_wud)

**Comment by fmartinou** [comment]
Hi,

It's clear that there is a configuration issue between the registry you use (Docker hub?) and the credentials you provide.

Can you share your configuration and a bit more logs, please?

**Comment by poudenes** [comment]
I have same issue. Here my docker config:

```
version: "3.9"
services:
  wud:
    image: fmartinou/whats-up-docker
    container_name: wud
    hostname: wud
    restart: always
    ports:
      - 3555:3000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volumeUSB1/usbshare/docker/wud:/store
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: Europe/Amsterdam
      PUID: 1026
      PGID: 100
      WUD_WATCHER_LOCAL_WATCHBYDEFAULT: false
      WUD_REGISTRY_HUB_AUTH: "SECURE" (username:password in Base64 encode)
      WUD_TRIGGER_MQTT_MOSQUITTO_URL: "mqtt://172.30.33.11:1883"
      WUD_TRIGGER_MQTT_MOSQUITTO_HASS_ENABLED: "true"
      WUD_TRIGGER_MQTT_MOSQUITTO_USER: "USER"
      WUD_TRIGGER_MQTT_MOSQUITTO_PASSWORD: 'PASS'
    mem_limit: 128m
    mem_reservation: 50m
    cpu_shares: 256
    security_opt:
      - no-new-privileges=true
    read_only: true
    networks:
       synology:
         ipv4_address: 172.30.33.121
networks:
  synology:
    external: true
```
