### ISSUE TITLE
Linuxserver  repo

### ISSUE THREAD

**Issue by Tyrian81** [getwud/wud#220]
I have 3 sensors that do not play well in home assistant (unknown state)

They're all from the linuxserver/  repo  , can i somehow add them ?

containers: Heimdall, Ubooquity, Code-server

they give a :

Error
Unsupported Registry unknown

**Comment by fmartinou** [comment]
Are these containers pulled from [lscr.io](https://fleet.linuxserver.io/)?

If so, the support of this registry is not automatically enabled because it requires you to provide Github credentials.

So you have to configure it first.
[See the documentation here](https://fmartinou.github.io/whats-up-docker/#/configuration/registries/lscr/).

**Comment by royto** [comment]
I had same pb.

I have well configure WUD with a personal token.

I'm using latest version of WUD.

error in logs:
`WARN whats-up-docker/watcher.docker.local: Error when processing (Unsupported Registry unknown) (container=local_heimdall)`

my docker compose for heimdall:

```
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data/:/config
    ports:
      - 8082:80
      - 8443:443
    restart: unless-stopped
```
