### ISSUE TITLE
whats-up-docker fails to read its own labels?

### ISSUE THREAD

**Issue by Percy2Live** [getwud/wud#235]
I'm not sure whether this is a real issue or a misconfiguration.
I added the wud.tag.exclude label to the wud container itself with the regex expression '[a-zA-Z]'. This works fine for some other containers, but wud keeps listing the "feature__225_focus_login_input_on_load" tag as the latest. According to my regex understanding this label should definitely be ignored. What is the best practice to only get the latest major revisions of itself listed on the wud overview?

**Comment by fmartinou** [comment]
Hi,

There is no difference between how `wud` reads its own labels compared to other containers.

Can you get me your exact configuration?

Personally I use the following regex to get `wud` available updates:
```
services:
   wud:
        image: fmartinou/whats-up-docker:6.0.2
        labels:
            - 'wud.tag.include=^\d+\.\d+\.\d+$$'
            - 'wud.link.template=https://github.com/fmartinou/whats-up-docker/releases/tag/$${major}.$${minor}.$${patch}'
            - 'wud.display.name=WUD'
            - 'wud.display.icon=mdi:docker'
```

**Comment by Percy2Live** [comment]
in the meantime I already adapted the configuration and it's quite close to your suggestion - at least the regex part:


```
services:
  whatsupdocker:
    image: fmartinou/whats-up-docker:6.0.2
    container_name: Whats-Up-Docker
    security_opt:
      - no-new-privileges=true
    read_only: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /volume1/Docker/Volumes/WUD:/store
    ports:
      - 3000:3000
    mac_address: 12:12:12:23:23:64
    networks:
      default:
        ipv4_address: 192.168.XXX.XXX 
    labels:
      - wud.tag.include = \d+\.\d+\.\b(0)$

networks:
  default:
    external:
      name: custom_docker_network
```

Unfortunately this still leads to:

![image](https://user-images.githubusercontent.com/63621052/224537811-706e37de-7412-4f1c-83c3-d96e330768e8.png)
