### ISSUE TITLE
Labels too long in homeassistant 

### ISSUE THREAD

**Issue by ioull** [getwud/wud#308]
Since the last homeassistant update, the name of the entity is concatained with the name of the device : 
For example instead of "adguardhome", I get "What's up docker? Adguardhome"

Here is a screenshot : 
![image](https://github.com/fmartinou/whats-up-docker/assets/6410144/3bdf110b-6978-4d35-9b78-2316b97e466a)

**Comment by laberning** [comment]
I was struggling with the same, for now solved it with the replace filter `| regex_replace('What\'s
          up docker\? ','')`

This is how it looks in the card configuration, I'm using some custom cards, but this should work with other configurations as well:

```yaml
type: custom:auto-entities
card:
  title: Available Updates
  type: entities
show_empty: false
filter:
  include:
    - entity_id: update.*
      attributes:
        update_available: true
      options:
        type: custom:template-entity-row
        name: >-
          {{ state_attr(config.entity, 'friendly_name')| regex_replace('What\'s
          up docker\? ','') }}
        state: >-
          {{ state_attr(config.entity, 'installed_version' )}} → {{
          state_attr(config.entity, 'latest_version') }}
        icon: mdi:update
```
<img width="495" alt="Bildschirmfoto 2023-09-29 um 09 53 59" src="https://github.com/fmartinou/whats-up-docker/assets/151194/f48e0113-fdaa-445b-b621-9d708992cd64">
