### ISSUE TITLE
Linuxserver image naming headaches

### ISSUE THREAD

**Issue by KeithB** [getwud/wud#310]
Hi!

Not a WUD issue specifically but having a few headaches with recommendations for label structure when using Linuxserver images (from GHCR in this instance though I believe they keep it consistent across registries). I had a rummage through previous issues and the HA forum thread but couldn't see anything that might help so apologies if this is in the wrong place...

First one is that Linuxserver images seem to all trigger the pre-release semver tagging - their release versioning essentially being <original-app>-<linuxserver base>. For example - 10.11.4-r0-ls110 for MariaDB. I've tried a couple of different regexes to try and limit what WUD considers as parts of the version but no luck. Currently using the regex below to try and force it to treat the Linuxserver base as part of the patch level:
```
version: "3"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb:10.11.4-r0-ls109
    container_name: mariadb
    environment:
      - PUID=803
      - PGID=803
      - TZ=Europe/London
    volumes:
      - /containers/volumes/mariadb/config:/config
    ports:
      - 3307:3306
    restart: unless-stopped
    labels:
      - 'wud.watch=true'
      - 'wud.tag.include=^([0-9]\d*)\.([0-9]\d*)\.([0-9]\d*-r[0-9]-ls[0-9]\d*)$$' 
```

The other, that might be linked, was it identifying a minor version downgrade (3.0.10.1567-ls197 down to 3.0.9.1549-ls180) instead of an update to 3.0.10.1567-ls203 from this regex:
`^([0-9]\d*)\.([0-9]\d*)\.([0-9]\d*).([0-9]\d*)-ls([0-9]\d*)$$`

I do have a few other questions and thought on a possible enhancement but will keep this topic limited to the regex headache for Linuxserver images.

Thanks!

**Comment by fmartinou** [comment]
Hi,

Just to clarify; the `wud.tag.include` regex is only there to filter what versions should be considered for comparing to the local version.

Capturing groups will have no effects there (do not expect the first group to be considered as the major version, the 2nd as the minor version, etc).

For "exotic tag naming" (as linuxserver tags are...), your best luck is to deal with the `wud.tag.transform` label.
This label will allow you to define an extra function to map weird tag names to something more usable.

Basically, it will allow you to indicate a regex with capture groups and a string template to use the captured values as you want.

Based on you example, here is a basic working proposal:

```yaml
version: "3"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb:10.11.4-r0-ls109
    ...
    labels:
      - 'wud.watch=true'
      - 'wud.tag.include=^\d+\.\d+\.\d+-.*$$'            # Keep only tags matching the same pattern as 10.11.4-r0-ls109
      - 'wud.tag.transform=^(\d+\.\d+\.\d+)-.*$$ => $$1' # Transform to something like 10.11.4 to consider mariadb versions only
```

In this example, I just strip all the `-r0-ls109` part to only be notified when a major/minor/patch of mariadb is available but you can adjust it to achieve the logic you want.

[Here is the related documentation](https://fmartinou.github.io/whats-up-docker/#/configuration/watchers/?id=transform-the-tags-before-performing-the-analysis)

I hope it will help you finding a solution to your problem 😃 .
