### ISSUE TITLE
Use docker socket proxy instead of mounting /var/run/docker.sock

### ISSUE THREAD

**Issue by mgite** [getwud/wud#317]
Can we add support to use [docker-socket-proxy](https://github.com/Tecnativa/docker-socket-proxy) container instead of using mount to /var/run/docker.sock for security purposes?

**Comment by kingp0dd** [comment]
been wanting this for a while

**Comment by ameer1234567890** [comment]
I have been using WUD with docker-socket-proxy and it works pretty well.

**Comment by kingp0dd** [comment]
What is your compose like?

**Comment by ameer1234567890** [comment]
Here is my compose file.

```
services:
  whatsupdocker:
    image: fmartinou/whats-up-docker
    container_name: whatsupdocker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/pi/docker/whatsupdocker:/store
    environment:
      - WUD_WATCHER_NAS2_SOCKET=/var/run/docker.sock
      - WUD_WATCHER_NAS2_WATCHALL=true
      - WUD_WATCHER_FIG_HOST=fig.lan
      - WUD_WATCHER_FIG_WATCHALL=true
    ports:
      - 3000:3000
    restart: unless-stopped
```

**Comment by jrbarronumd** [comment]
I've been using the socket proxy for a remote server and it has been working well.  My local watcher uses the direct socket mount, but it should work the same doing it local vs remote.  There is some configuring to the proxy container as well, which I pulled an issue here for, and @fmartinou helped out with (#354).  My compose entries are below.  Hope this helps.


Host Machine:
 ```
services:
    whatsupdocker:
      container_name: wud
      image: ghcr.io/fmartinou/whats-up-docker:6.3.0
      restart: unless-stopped
      security_opt:
        - no-new-privileges:true
      healthcheck:
        test: wget --no-verbose --tries=1 --no-check-certificate --spider http://localhost:3000
        interval: 10s
        timeout: 10s
        retries: 3
        start_period: 10s  
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - $DOCKERDIR/whats-up-docker:/store
      environment:
        - WUD_WATCHER_local_SOCKET=/var/run/docker.sock
        - WUD_WATCHER_remote_HOST=10.x.x.x
 ```

Remote machine
```
services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:0.1.1
    container_name: dockerproxy
    restart: unless-stopped
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - LOG_LEVEL=debug
      - CONTAINERS=1 # Allow access to viewing containers
      - ALLOW_START=1
      - ALLOW_STOP=1
      - IMAGES=1
      - POST=0 # Disallow any POST operations (effectively read-only)
```

**Comment by jrbarronumd** [comment]
@kingp0dd It's been a bit since I set it up, but I think because 2375 is the default port for the docker socket to be exposed (whether using the proxy or not).  If exposing the socket proxy on a different port, you would have to specify in the WUD config.

**Comment by kingp0dd** [comment]
> @kingp0dd It's been a bit since I set it up, but I think because 2375 is the default port for the docker socket to be exposed (whether using the proxy or not). If exposing the socket proxy on a different port, you would have to specify in the WUD config.

that makes much more sense now. thanks mate!

**Comment by cerealconyogurt** [comment]
Hi @kingp0dd, are you still having the problem? In my cases is working without any problem.

**Comment by kingp0dd** [comment]
Was there a recent update or change to support it? I haven't tried it yet

**Comment by cerealconyogurt** [comment]
I am not sure since this is the first time for me installing this app.
My setup indeed is using two socket proxies; one for the local machine and the second one for a remote machine:

>   WUD_WATCHER_NAS_HOST: xxx.xxx.0.2
      WUD_WATCHER_NAS_PORT: 2375
      WUD_WATCHER_NAS_WATCHALL: true
      WUD_WATCHER_DIETPI_HOST: xxx.xxx.1.73
      WUD_WATCHER_DIETPI_PORT: 2376
      WUD_WATCHER_DIETPI_WATCHALL: true

**Comment by FizzGiGG** [comment]
Well, I'm not the brightest bulb in the pack when it comes to *nix and docker and whatnot. I'm a Windows admin at heart, but I may have gotten this socket-proxy thing to work.

My issue was that I was receiving an error from WUD trying to connect to docker.sock, which I'm sure a lot of you have also experienced.

Error Access:
> whats-up-docker/watcher.docker.local: Unable to listen to Docker events [connect EACCES /var/run/docker.sock]

I went through the trouble of making sure all permissions were correct, and even though I set permissions to 777 (testing only) on the /var/run/docker.sock file, I was still receiving the access error. Crazy.

Based on _this_ issue I went and looked for examples of using the socket-proxy container and found a Linuxserver.io image that had a bit more documentation and is also from a registry I like and use a lot.

https://github.com/linuxserver/docker-socket-proxy

Using that image and digging into some other configs online from various sources, I came to the configuration below that no longer produces an error upon starting the container. It now tries to pull updated images, yet errors out. That's for another topic. Moving back on to this one...

There may be way more junk in my compose file than is absolutely necessary; I'm still trying to wrap my head around configuring it properly.

compose.yml important parts
```
services:
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: socket-proxy
    hostname: socket-proxy # I hate the random host names, security through obscurity be damned!
    environment:
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      # 0 to revoke access.
      # 1 to grant access.
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=1 WUD
      # Not always needed
      - ALLOW_START=1 # WUD, Portainer, etc.
      - ALLOW_STOP=1 # WUD, Portainer, etc.
      - ALLOW_RESTARTS=1 # WUD, Portainer, etc.
      - BUILD=1 # WUD, Portainer, etc.
      - COMMIT=0
      - CONFIGS=1 # WUD, Portainer, etc.
      - CONTAINERS=1 # WUD, Portainer, etc.
      - DISABLE_IPV6=1
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1 # WUD, Portainer, etc.
      - INFO=1
      - NETWORKS=1 # WUD, Portainer, etc.
      - NODES=0
      - PLUGINS=0
      - SERVICES=1 # WUD, Portainer, etc.
      - SESSION=0
      - SWARM=0
      - SYSTEM=1 # WUD, Portainer, etc.
      - TASKS=1
      - VOLUMES=1 # WUD, Portainer, etc.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run
    labels:
      - 'wud.tag.include=latest'

  wud:
    image: fmartinou/whats-up-docker:latest
    container_name: wud
    hostname: wud
    user: 1002:1005 # tried setting this while troubleshooting docker.sock connection issue, but left it so it matches my other container configs
    environment:
      - TZ=America/Chicago
      # Triggers Notifications
      - WUD_TRIGGER_SMTP_EMAIL_HOST=smtprelay
      - WUD_TRIGGER_SMTP_EMAIL_PORT=25
      - WUD_TRIGGER_SMTP_EMAIL_USER=wud@yayas.com
      - WUD_TRIGGER_SMTP_EMAIL_PASS=blank
      - WUD_TRIGGER_SMTP_EMAIL_FROM=wud@yayas.com
      - WUD_TRIGGER_SMTP_EMAIL_TO=mmhmmyep@gmail.com
      - WUD_TRIGGER_SMTP_EMAIL_TLS_ENABLED=false
      # Triggers Updates
      - WUD_TRIGGER_DOCKERCOMPOSE_UPDATE_FILE=/wud/compose.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_UPDATE_BACKUP=true
      - WUD_TRIGGER_DOCKERCOMPOSE_UPDATE_PRUNE=true
      - WUD_TRIGGER_DOCKERCOMPOSE_UPDATE_MODE=batch
      - WUD_TRIGGER_DOCKERCOMPOSE_UPDATE_DRYRUN=false
      - WUD_TRIGGER_DOCKERCOMPOSE_UPDATE_ONCE=false
      # Registries
      - WUD_REGISTRY_LSCR_USERNAME=menotyou
      - WUD_REGISTRY_LSCR_TOKEN=ghp_XMO========================4XR1
      - WUD_REGISTRY_GHCR_USERNAME=menotyou
      - WUD_REGISTRY_GHCR_TOKEN=ghp_Nsq=========================1FC
      - WUD_REGISTRY_HUB_LOGIN=menotyou
      - WUD_REGISTRY_HUB_TOKEN=dckr_==========================76Q6c
      # Watcher
      - WUD_WATCHER_LOCAL_CRON=0 7 * * *
      - WUD_WATCHER_LOCAL_WATCHBYDEFAULT=true
      - WUD_WATCHER_LOCAL_WATCHALL=false
      - WUD_WATCHER_LOCAL_SOCKET=tcp://socket-proxy:2375 # Are these two lines redundant? (1/2)
      - DOCKER_HOST=tcp://socket-proxy:2375                             # Are these two lines redundant? (2/2)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/stuffs/docker/compose.yml:/wud/compose.yml:rw
      - /home/stuffs/docker/wud/store:/store
    labels:
      - 'wud.tag.include=latest'
    ports:
      - 3001:3000 # 3000 already in use
    restart: unless-stopped
```

Maybe?

**Comment by lamiskin** [comment]
I have had success using the following configuration for only using docker-socket-proxy on the localhost.

```
services:

  whatsupdocker:
    image: fmartinou/whats-up-docker
    environment:
      - DOCKER_HOST=tcp://docker-socket-proxy:2375
    depends_on:
      - docker-socket-proxy

  docker-socket-proxy:
    image: ghcr.io/tecnativa/docker-socket-proxy
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    environment:
      - CONTAINERS=1
      - IMAGES=1
      - POST=0

```

I've excluded my networks etc, as they are specific to my setup.

**Comment by fmartinou** [comment]
Hi @mgite,

This is already fully supported!
You do not need to mount `/var/run/docker.sock` directly into WUD if you use a socket proxy like `tecnativa/docker-socket-proxy`.

To connect WUD to a Docker socket proxy:
```yaml
services:
  wud:
    image: getwud/wud:latest
    environment:
      - WUD_WATCHER_LOCAL_HOST=docker-socket-proxy
      - WUD_WATCHER_LOCAL_PORT=2375
```

Make sure the socket proxy permits GET and POST access to /containers/*, /images/*, and /events.

Closing as this feature is already supported by design.
