### ISSUE TITLE
Working with several docker compose

### ISSUE THREAD

**Issue by lordraiden** [getwud/wud#329]
I have around 10 docker compose files with containers that I want to update
According to the documentation
https://fmartinou.github.io/whats-up-docker/#/configuration/triggers/docker-compose/

Do I need to run a whats-up-docker instance for each docker compose? is there a way to update all of them from a single instance?

**Comment by fmartinou** [comment]
Hi,

In theory, configuring multiple "docker-compose triggers" should work 🤞.

**Comment by lordraiden** [comment]
> Hi,
> 
> In theory, configuring multiple "docker-compose triggers" should work 🤞.

I'm trying to make it work.

I want to monitor only an update 2 docker compose files "monitoring" and "administration"
I have this compose and I have added  "wud.watch: "true"" label to the 2 compose I want to monitor only.
Instead I get all my dockers and no triggers
![imagen](https://github.com/fmartinou/whats-up-docker/assets/17175395/aa4923c3-bf9e-47f1-bdfd-4af230cdac19)

What I'm doing wrong?

```
  whatsupdocker:
    image: fmartinou/whats-up-docker
    container_name: WhatsUpDocker
    <<: *config
    networks:
      eth1:
        ipv4_address: ${whatsupdocker_ip}
    environment:
      - TZ      
      - WUD_WATCHER_LOCAL_SOCKET=/var/run/docker.sock
     # - WUD_WATCHER_{watcher_name}_PORT
     # - WUD_WATCHER_{watcher_name}_HOST
      - WUD_TRIGGER_DOCKERCOMPOSE_MONITORING=/wud/docker-compose-monitoring.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_MONITORING_PRUNE=true
      - WUD_TRIGGER_DOCKERCOMPOSE_ADMINISTRATION=/wud/docker-compose-administration.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_ADMINISTRATION_PRUNE=true
    #  - WUD_WATCHER_LOCAL_CRON=0 1 * * *
      - WUD_WATCHER_LOCAL_WATCHBYDEFAULT=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/services/docker/Whats-up-docker:/store
      - /mnt/services/docker/docker-compose/Monitoring/docker-compose.yml:/wud/docker-compose-monitoring.yml
      - /mnt/services/docker/docker-compose/Administration/docker-compose.yml:/wud/docker-compose-administration.yml
    ports:
      - 3000:3000
    labels:
      <<: *labels
      net.unraid.docker.icon: "https://i.imgur.com/eIUvk2Y.png"
      net.unraid.docker.webui: "http://${whatsupdocker_ip}:3000/"
```
