### ISSUE TITLE
custom text for specific containers with docker labels

### ISSUE THREAD

**Issue by xsolinsx** [getwud/wud#330]
Hi, I'd like the possibility to specify custom text when notifying updates for a container.
For example, I'd like to remind myself to update the [sablier traefik plugin](https://plugins.traefik.io/plugins/633b4658a4caa9ddeffda119/sablier) when I update [sablier container](https://github.com/acouvreur/sablier/).
So the default update-notification text should not be replaced wholly, it would just need to be integrated with a custom one for the specific container

Maybe something like this for a docker compose
```yaml
.......
labels:
  wud.notify.customtext: Check also for updates on the plugin!
.......
```
