### ISSUE TITLE
Check Updated Image for custom tag syntax may have some issues.

### ISSUE THREAD

**Issue by catfishlty** [getwud/wud#344]
## Desc
I use the latest image tag for my compose file, but the notification show me the image with the older version tag, so I'm confused that the checking logic may have some issues.

## docker-compose.yml
```
chromium:
    image: linuxserver/chromium:cf1f086c-ls51
    container_name: chromium
    labels:
      - wud.display.name=Chromium
      - wud.tag.include=^.*?\-ls\d+$$
```

## Notification
```
Container chromium running with tag cf1f086c-ls51 can be updated to tag 98239515-ls42
```

## Info form docker hub
1. [cf1f086c-ls51](https://hub.docker.com/layers/linuxserver/chromium/cf1f086c-ls51/images/sha256-d13847e44b79b2ee370ae3399261af4579f7e00063d238f9afa2214f38f902bf?context=explore)
2. [98239515-ls42](https://hub.docker.com/layers/linuxserver/chromium/98239515-ls42/images/sha256-5562f09778bf23cdec69e16eae96e3777e46605eef36c19356aaa0455e6614d3?context=explore)
