### ISSUE TITLE
Watching base image ?

### ISSUE THREAD

**Issue by r3mi** [getwud/wud#353]
Hello,
thanks for What's up Docker, very useful !
Question: is there a way to watch "base" image ?

Sometime, I need to customize released images, e.g.
```dockerfile
FROM imageA:versionA
RUN some small customization
```
In that example, is there an easy way to watch for "imageA" ?

More complex example, when "merging" 2 images:
```dockerfile
FROM imageB:versionB AS bb
FROM imageC:versionC
COPY --from=bb /some /stuff
```
In that example, is there an easy way to watch for "imageB" and "imageC" ?

Thanks !

**Comment by fmartinou** [comment]
Hi,

Right now, there is no possibility to watch base images.

`wud` is only watching containers, not Dockerfiles.

I'm not aware of any possible solution to get the `FROM` information from a container; do you?

**Comment by r3mi** [comment]
hello, thanks,
or may be , would it make sense to add a specific label to provide the image reference ?
e.g.
```yml
services:
  mariadb:
  build:
    dockerfile_inline: |
      FROM mariadb:10.4.5
      RUN some customization  
    ...
  labels:
    - wud.image=mariadb:10.4.5
```
