### ISSUE TITLE
Notifications for Individual Hosts

### ISSUE THREAD

**Issue by SamFusco** [getwud/wud#421]
I think I might be missing something here, but is there a way to set notifications based off of hosts? I have multiple hosts configured as watchers but I can't seem to setup notifications to be:

`$${name} on $${hostname} has a new update. It can be updated from version $${local} to $${remote}`

```yaml
services:
  wud:
    image: fmartinou/whats-up-docker:latest
    container_name: wud
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/local/share/certificates:/certs:ro
    environment:
      - TZ=UTC/ETC
      - WUD_REGISTRY_HUB_LOGIN=${USERNAME}
      - WUD_REGISTRY_HUB_PASSWORD=${PASSWORD}
      - WUD_TRIGGER_DISCORD_notification_URL=${LINK}
      - WUD_TRIGGER_DISCORD_notification_BOTUSERNAME=Container-Updates
      - WUD_TRIGGER_DISCORD_notification_SIMPLETITLE=New image found for $${name}
      - WUD_TRIGGER_DISCORD_notification_SIMPLEBODY=$${name} has a new update. It can be updated from version $${local}
      - WUD_WATCHER_host1_SOCKET=/var/run/docker.sock
      - WUD_WATCHER_host2_HOST=host2.mydomain
      - WUD_WATCHER_host2_PORT=2376
      - WUD_WATCHER_host2_CAFILE=/certs/host2/ca.pem
      - WUD_WATCHER_host2_CERTFILE=/certs/host2/cert.pem
      - WUD_WATCHER_host2_KEYFILE=/certs/host2/key.pem
      - WUD_WATCHER_host3_HOST=host3.mydomain
      - WUD_WATCHER_host3_PORT=2376
      - WUD_WATCHER_host3_CAFILE=/certs/host3/ca.pem
      - WUD_WATCHER_host3_CERTFILE=/certs/host3/cert.pem
      - WUD_WATCHER_host3_KEYFILE=/certs/host3/key.pem
    ports:
     - 13000:3000
```

Is there a key trigger I am missing maybe?
