### ISSUE TITLE
WUD doesn't read from deploy labels for Docker Swarm

### ISSUE THREAD

**Issue by mAAdhaTTah** [getwud/wud#436]
Perhaps a feature request, at a minimum a note for others, but I use Traefix to proxy to my apps, and my docker-compose all have some version of this:

```
    deploy:
      labels:
        - "traefik.http.routers.nzbhydra2.rule=Host(`{{ service.server_name }}`)"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.services.nzbhydra2.loadbalancer.server.port=5076"
        - "traefik.http.routers.nzbhydra2.service=nzbhydra2"
```

I originally added the wud labels to it:

```
    deploy:
      labels:
        - 'wud.tag.include=^\d+\.\d+\.\d+$$'
        - "traefik.http.routers.nzbhydra2.rule=Host(`{{ service.server_name }}`)"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.services.nzbhydra2.loadbalancer.server.port=5076"
        - "traefik.http.routers.nzbhydra2.service=nzbhydra2"
```

And I was wracking my brain on why it wasn't working, until I realized the labels needed to be on the container:

```
    labels:
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'
    deploy:
      labels:
        - "traefik.http.routers.nzbhydra2.rule=Host(`{{ service.server_name }}`)"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.services.nzbhydra2.loadbalancer.server.port=5076"
        - "traefik.http.routers.nzbhydra2.service=nzbhydra2"
```

If it were easy/possible to read from the deploy labels, this would be a little cleaner (and perhaps less confusing), although, since I was able to make it work, less of an issue.
