### ISSUE TITLE
postgres:16 being offered 17rc1-bullseye

### ISSUE THREAD

**Issue by willowless** [getwud/wud#476]
Hi there. New to WUD. Love it.

I have postgres:16 set up and have no interest in changing it to version 17; however WUD is telling me my 16 branch is out of date suggesting I should upgrade to 17rc1-bullseye.

Is there a setting I can set to make it stick to the branch i've chosen?

**Comment by fmartinou** [comment]
Hi,

Welcome on board 😃 

You can achieve that by playing with `wud.tag.include` / `wud.tag.exclude` tags [as explained in the doc](https://getwud.github.io/wud/#/configuration/watchers/).

For example,
```yaml
    postgres:
        image: postgres:16
        labels:
            - 'wud.tag.include=^16$$'
```

If you still want to upgrade minor versions, you can switch to the 16.x tags:
```yaml
    postgres:
        image: postgres:16.4
        labels:
            - 'wud.tag.include=^16\.\d+$$'
```
