### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Shark1979xxx** [getwud/wud#485]
Is it possible to exclude a package from checking?

thx!

**Comment by Shark1979xxx** [comment]
I try with:
 - WUD.TAG.EXCLUDE=ghcr.io/alexjustesen/speedtest-tracker:v0.11.17

but not work.

Please help me

**Comment by fmartinou** [comment]
If you just want to exclude one of your container from being watched, you can add the label `wud.watch=false` to it.

Ex:

```yaml
services:
  speedtest:
    image: ghcr.io/alexjustesen/speedtest-tracker:v0.11.17
    labels:
      - 'wud.watch=false'
```

**Comment by Shark1979xxx** [comment]
This is my stack:
```
services:
  whatsupdocker:
    image: getwud/wud
    container_name: WUD
    security_opt:
      - no-new-privileges=true
    read_only: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /volume1/docker/wud:/store:rw
    ports:
      -xxxx:xxxx
    environment:
     - WUD_TRIGGER_SMTP_GMAIL_HOST=smtp.gmail.com
     - WUD_TRIGGER_SMTP_GMAIL_PORT=465
     - WUD_TRIGGER_SMTP_GMAIL_USER=
     - WUD_TRIGGER_SMTP_GMAIL_PASS=
     - WUD_TRIGGER_SMTP_GMAIL_FROM=
     - WUD_TRIGGER_SMTP_GMAIL_TO=
     - WUD_TRIGGER_SMTP_GMAIL_TLS_ENABLED=true
     - WUD_TRIGGER_SMTP_GMAIL_SIMPLETITLE=
     - WUD_TRIGGER_SMTP_GMAIL_SIMPLEBODY=
  speedtest:
    image: ghcr.io/alexjustesen/speedtest-tracker:v0.11.17
    labels:
      - 'wud.watch=false'
```

and wud keep checking the speedtest.
Where am I wrong?
