### ISSUE TITLE
Remove the 'wud' prefix for Home Assistant

### ISSUE THREAD

**Issue by deanpribetic** [getwud/wud#486]
I am connecting wud to Home Assistant via MQTT and whenever the entities display they have 'wud' prepended to the name…

![CleanShot 2024-11-14 at 13 58 50](https://github.com/user-attachments/assets/31056de0-f629-485e-80d8-8c090d34e057)

I don't have anything special going on with the config…

![CleanShot 2024-11-14 at 14 04 01](https://github.com/user-attachments/assets/18056c2b-b3bf-4041-a627-d20c426f780b)

and in the Uptime Kuma docker-compose…

```
---
version: "2.1"
services:
  uptime_kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime_kuma
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    restart: always
    labels:
      - wud.display.name=Uptime Kuma
      - wud.display.icon=si:uptimekuma
```

is there a way I can remove that 'wud' prefix from the entity name?
