### ISSUE TITLE
Triggers not working

### ISSUE THREAD

**Issue by deanfourie1** [getwud/wud#495]
I am defining triggers like 

```
version: "3"
services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    environment:
      - WUD_TRIGGER_MQTT_MOSQUITTO_URL=mqtt://mqttserver:1883
      - WUD_TRIGGER_MQTT_MAQIATTO_USER=
      - WUD_TRIGGER_MQTT_MAQIATTO_PASSWORD=
      - WUD_TRIGGER_MQTT_MOSQUITTO_HASS_ENABLED=true
      - WUD_TRIGGER_MQTT_MOSQUITTO_HASS_DISCOVERY=true
networks: {}
```

But, when I visit the UI, it does not show any triggers present. I have tried the same for SMTP, with the same result.

Am I missing something?

Thanks

<img width="597" alt="image" src="https://github.com/user-attachments/assets/173cda0a-4e3c-47fd-8763-f5cb142f2e35">
