### ISSUE TITLE
Does it make sense to add a param that takes into consideration the date of the tag?

### ISSUE THREAD

**Issue by rafapirotto** [getwud/wud#498]
Basically my use case is easy. Just a couple of containers with fixed semver tags like: 5.0.2. My problem is that I have a container (qBittorrent from linuxserver) that for same reason has a 20.04.1 tag. This tag is 3 years old. If there was a label I could include to tell wud to only consider tags whose date is after mine, that'd be great. Just to double check, there isn't any way to do this now right?

Thanks!

**Comment by fmartinou** [comment]
Hi,

I presume that your issue about _qBittorrent_ is caused by the fact that they changed the way they release (from calver to semver obviously) so 20.04.1 pops up as false-positive.

You can get away with that by using an exclude filter.
For example:
```
services:
  qBittorrent:
    image: linuxserver/qbittorrent:xxx
    ...
    labels:
      - wud.tag.exclude=^20.*$$
```
