### ISSUE TITLE
Can't login to web ui "Some authentications failed to register"

### ISSUE THREAD

**Issue by ValentinDrean** [getwud/wud#499]
Hi,

I get stuck to login page and there are no way to enter login/password because text/login boxes aren't there, see image down my post.

Here is my compose :
```
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    environment:
      - WUD_AUTH_BASIC_ROZA_USER=roza
        WUD_AUTH_BASIC_ROZA_HASH=$$apr1$$gmapzc1i$$9SftU94I59lIkviedxTVe/
      - WUD_LOG_FORMAT=text
      - WUD_TRIGGER_SMTP_SAGEGANDI_FROM=XXX
      - WUD_TRIGGER_SMTP_SAGEGANDI_HOST=mail.XXX
      - WUD_TRIGGER_SMTP_SAGEGANDI_PASS=$$apr1$$ctw10qyx$$
      - WUD_TRIGGER_SMTP_SAGEGANDI_PORT=465
      - WUD_TRIGGER_SMTP_SAGEGANDI_TLS_ENABLED=true
      - WUD_TRIGGER_SMTP_SAGEGANDI_TO=XXX
      - WUD_TRIGGER_SMTP_SAGEGANDI_USER=XXX
```

Docker version 27.3.1, build ce12230, tried both librewolf & firefox, only with adblockers btw 

![https://bon.pointorg.org/-CeQcBamr3L/Screenshot_2024-11-29_17-53-31.png](https://bon.pointorg.org/-CeQcBamr3L/Screenshot_2024-11-29_17-53-31.png)

Mails hash credentials for notifications are ok though, I tried both htpasswd & website method for web ui login hash but I always get this problem, I guess there is something enormous I don't understand here, but I'm ok without gui, as I just need mail (:

There is a WARN log : 
`16:29:59.121  WARN whats-up-docker/registry: Some authentications failed to register (Error when registering component basic ("hash" is required))`

**Comment by fmartinou** [comment]
Hi, a `-` seems to be missing in you compose file

```yaml
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    environment:
      - WUD_AUTH_BASIC_ROZA_USER=roza
        WUD_AUTH_BASIC_ROZA_HASH=$$apr1$$gmapzc1i$$9SftU94I59lIkviedxTVe/ <---- HERE!!!
      - WUD_LOG_FORMAT=text
      - WUD_TRIGGER_SMTP_SAGEGANDI_FROM=XXX
      - WUD_TRIGGER_SMTP_SAGEGANDI_HOST=mail.XXX
      - WUD_TRIGGER_SMTP_SAGEGANDI_PASS=$$apr1$$ctw10qyx$$
      - WUD_TRIGGER_SMTP_SAGEGANDI_PORT=465
      - WUD_TRIGGER_SMTP_SAGEGANDI_TLS_ENABLED=true
      - WUD_TRIGGER_SMTP_SAGEGANDI_TO=XXX
      - WUD_TRIGGER_SMTP_SAGEGANDI_USER=XXX
```

Fixed version
```yaml
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    environment:
      - WUD_AUTH_BASIC_ROZA_USER=roza
      - WUD_AUTH_BASIC_ROZA_HASH=$$apr1$$gmapzc1i$$9SftU94I59lIkviedxTVe/
      - WUD_LOG_FORMAT=text
      - WUD_TRIGGER_SMTP_SAGEGANDI_FROM=XXX
      - WUD_TRIGGER_SMTP_SAGEGANDI_HOST=mail.XXX
      - WUD_TRIGGER_SMTP_SAGEGANDI_PASS=$$apr1$$ctw10qyx$$
      - WUD_TRIGGER_SMTP_SAGEGANDI_PORT=465
      - WUD_TRIGGER_SMTP_SAGEGANDI_TLS_ENABLED=true
      - WUD_TRIGGER_SMTP_SAGEGANDI_TO=XXX
      - WUD_TRIGGER_SMTP_SAGEGANDI_USER=XXX
```
