### ISSUE TITLE
Pick specific trigger for a specific container

### ISSUE THREAD

**Issue by mindofbeholder** [getwud/wud#502]
Is it possible to say which triggers I want to apply to which containers?

eg I don't mind if my dashboard gets all updates automatically but I don't want my authentication tool to get anything but minor updates & patches automatically.

**Comment by fmartinou** [comment]
Hi,

Unfortunately, it's not supported.
I find your use case valid; I tag your issue as "enhancement".
(I don't have any ETA though...)

**Comment by fmartinou** [comment]
Implemented.

Examples:

```yaml
services:

  traefik1:
    image: traefik:3.0.0
    labels:
      - wud.trigger.include=ntfy.one:major

  traefik2:
    image: traefik:3.0.0
    labels:
      - wud.trigger.include=ntfy.two

  traefik3:
    image: traefik:3.0.0
    labels:
      - wud.trigger.exclude=ntfy.three
```

An additional tab has been added to the UI to give a look at the triggers associated to each container
![image](https://github.com/user-attachments/assets/e54add12-7e0e-4471-babb-d41e7b5fc8e2)
