### ISSUE TITLE
Discrepancy between GUI and Home Assistant

### ISSUE THREAD

**Issue by LorenKeagle** [getwud/wud#510]
Using WUD 7.1.1, I have a situation where the WUD GUI is correctly indicating that there is no update available for a container, but the MQTT telemetry to Home Assistant is still indicating one:

![Screenshot 2024-12-14 at 2 30 43 AM](https://github.com/user-attachments/assets/ca84eeac-6fbb-4bf4-baf0-1d8907f0bb5c)

![Screenshot 2024-12-14 at 2 30 22 AM](https://github.com/user-attachments/assets/674cc70b-ed33-4c84-838c-05888805eda6)

Here is my WUD compose file:

```
services:
  whatsupdocker:
    image: getwud/wud:7.1.1
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    environment:
      - WUD_WATCHER_LOCAL_WATCHALL=true
      - WUD_TRIGGER_MQTT_MOSQUITTO_URL=mqtt://xxx.xxx.xxx.xxx:1883
      - WUD_TRIGGER_MQTT_MOSQUITTO_HASS_ENABLED=true
      - WUD_TRIGGER_MQTT_MOSQUITTO_HASS_DISCOVERY=true
      - WUD_TRIGGER_MQTT_MOSQUITTO_USER=**********
      - WUD_TRIGGER_MQTT_MOSQUITTO_PASSWORD=**********
      - WUD_REGISTRY_LSCR_USERNAME=**********
      - WUD_REGISTRY_LSCR_TOKEN=**********
    labels:
      - 'wud.tag.include=^\d+\.\d+\.\d+$'
      - 'wud.watch.digest=true'
   
```

And here is the compose entry for the container in question:

```
  unifi-db:
    image: mongo:7
    container_name: unifi-db
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped
    labels:
      - 'wud.tag.include=^7+\.\d+\.\d+$'
      - 'wud.watch.digest=true'
```

This may be an edge condition related to the usage of the "mongo:7" tag to pull the latest version of mongo 7.x.x.  I have a feeling that this is due to WUD blindly reporting "current version = 7" vs "latest version = 7.0.15" in the MQTT message.  Is it not possible for WUD to figure out the actual version that is currently installed using the image ID? I was hoping that would be handled with the "wud.watch.digest=true" configuration, as that flag is supposed to look up all images from the repository.
