### ISSUE TITLE
Broke monitoring/README.md healthcheck implementation

### ISSUE THREAD

**Issue by davidosomething** [getwud/wud#524]
in 38f0ed6239255f2104c2cb59c62d224492123eed

`Dockerfile` https://github.com/getwud/wud/blob/main/Dockerfile#L2
was changed from alpine to node slim
`FROM node:23-slim as base`

which does not ship with `wget` or `curl`
So the healthcheck from the docs https://github.com/getwud/wud/blob/main/docs/monitoring/README.md#example
does not work

As an alternative, can just use node to test service is up

```yaml
    healthcheck:
      test: node --eval "fetch('http://localhost:3000').catch(() => process.exit(1))"
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
```
