### ISSUE TITLE
Trigger docker compose don't update file

### ISSUE THREAD

**Issue by kinouzero** [getwud/wud#546]
Hi,

I don't understand why, on the version 7.2.0 this feature worked but when I switched to main version it stopped fully working.

The file isn't modified but the target container is updated with the new image, and no backup file is created.

Here my docker-compose :

```
wud:
    <<: [*basic, *extra-hosts, *network-zero, *restart-always]
    container_name: ${WUD_NAME}
    environment:
      TZ: ${TZ}
      WUD_AUTH_OIDC_AUTHENTIK_CLIENTID: ${WUD_AUTH_OIDC_AUTHENTIK_CLIENTID}
      WUD_AUTH_OIDC_AUTHENTIK_CLIENTSECRET: ${WUD_AUTH_OIDC_AUTHENTIK_CLIENTSECRET}
      WUD_AUTH_OIDC_AUTHENTIK_DISCOVERY: ${WUD_AUTH_OIDC_AUTHENTIK_DISCOVERY}
      WUD_AUTH_OIDC_AUTHENTIK_REDIRECT: ${FALSE}
      WUD_LOG_LEVEL: ${LOG_LEVEL}
      WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_AUTO: ${FALSE}
      WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_BACKUP: ${TRUE}
      WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_FILE: ${WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_FILE}
      WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_PRUNE: ${TRUE}
      WUD_TRIGGER_SLACK_ZERO_CHANNEL: ${WUD_TRIGGER_SLACK_ZERO_CHANNEL}
      WUD_TRIGGER_SLACK_ZERO_TOKEN: ${WUD_TRIGGER_SLACK_ZERO_TOKEN}
      WUD_WATCHER_LOCAL_SOCKET: ${DIR_DOCKER_SOCKET}
      WUD_WATCHER_MQTT_HOST: ${MQTT_HOST}
    healthcheck:
      <<: *healthcheck-basic
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
    image: getwud/wud:main
    labels:
      <<: *label-wud-false
      wud.display.icon: 'sh-whats-up-docker'
      wud.display.name: 'Whats Up Docker'
    volumes:
      - ${DIR_APPDATA}/wud:/store
      - ${DIR_DOCKER_SOCKET}:${DIR_DOCKER_SOCKET}:ro
      - ${DIR_LOCALTIME}:${DIR_LOCALTIME}:ro
      - ${DIR_HOME}/.docker/compose:/compose
 ```

The docker-compose.yml file is well mounted in the container.
