### ISSUE TITLE
Question: How to schedule multiple container updates on separate schedules?

### ISSUE THREAD

**Issue by kaljade** [getwud/wud#555]
Hi there,

Sorry for the noob question, but I'm wanting to setup WUD to automatically update my docker containers on a schedule:

Here's my docker-compose.yml file:

```
services:
  whatsupdocker:
    image: getwud/wud
    container_name: whatsupdocker
    environment:
        - WUD_TRIGGER_SMTP_GMAIL_HOST=smtp.gmail.com
        - WUD_TRIGGER_SMTP_GMAIL_PORT=465
        - WUD_TRIGGER_SMTP_GMAIL_USER=******@gmail.com
        - WUD_TRIGGER_SMTP_GMAIL_PASS=**** **** **** ****
        - WUD_TRIGGER_SMTP_GMAIL_FROM=******@gmail.com
        - WUD_TRIGGER_SMTP_GMAIL_TO=example@email.com
        - WUD_TRIGGER_SMTP_GMAIL_TLS_ENABLED=true 
        - TZ=Australia/Sydney
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3000:3000
    restart: unless-stopped
```
I have two docker containers: WUD, and Hue Scheduler:
```
docker ps
CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS                    PORTS                                       NAMES
31ef6689a089   getwud/wud                           "/usr/bin/entrypointÃ¢Â¦"   37 minutes ago   Up 37 minutes (healthy)   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   whatsupdocker
81f94afb1123   stefanvictora/hue-scheduler:0.12.1   "java -jar hue-schedÃ¢Â¦"   13 days ago      Up 51 minutes                                                         hue-scheduler
```
What I would like to do is check/update WUD at * 15 * * * and Hue Scheduler at * 16 * * * I have gone through the help docs and can see how you setup a watcher for checking: WUD_WATCHER_{watcher_name}_CRON and also that you can set a  dockercompose trigger to automatically update containers, but I'm not too sure how to tie it all together.

As you can tell, I am very new to Docker so any help would be greatly appreciated.

Cheers,

Kal
