### ISSUE TITLE
[Feature Request]: Link to release page of images

### ISSUE THREAD

**Issue by mocdaniel** [getwud/wud#573]
I would love to have a link to the release page of a monitored image in the UI and notifications to quickly learn about changes introduced by pending upgrades.

This could be configurable e.g. via container labels on the monitored service, and templated to point at the release detected by WUD.

Consider this:

```yaml
services:
  whatsupdocker:
    container_name: whats-up-docker
    image: getwud/wud:8.0.0
    labels:
      wud.tag.include: ^\d+\.\d+\.\d+$$
      wud.release: https://github.com/getwud/wud/releases/tag
```

WUD would internally add the detected pending upgrade and surface the result (i.e. `https://github.com/getwud/wud/releases/tag/8.0.0`) where needed.
