### ISSUE TITLE
Registries not connecting..

### ISSUE THREAD

**Issue by eximo84** [getwud/wud#578]
Updated to the latest docker image, however errors in the log causing my containers to not be picked up.  Seems to stem from HUB not connecting with my base64 auth token

```
WARN whats-up-docker/registry: Some registries failed to register (Error when registering component hub ("public" is not allowed))

WARN whats-up-docker/watcher.docker.local: Error when trying to get the list of the containers to watch (Error when validating container properties ValidationError: "image.registry.url" is required)
```

My compose

```
services:
  whats-up-docker:
    image: fmartinou/whats-up-docker
    container_name: whats-up-docker
    hostname: whats-up-docker
    restart: always
    env_file: .env
    ports:
      - 3001:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dockerdata/storage/whats-up-docker:/store

networks:
  default:
    name: $MY_DEFAULT_NETWORK
    external: true
  reverse_proxy:
    name: $MY_REVERSEPROXY_NETWORK
    external: true
```

my .env (redacted)

```
# GENERAL
MY_DEFAULT_NETWORK=system_services
MY_REVERSEPROXY_NETWORK=reverse_proxy
MY_DOMAIN=my.fqdn
TZ=XX/XX
PGID=XXX
PUID=XXX

# WHATS-UP-DOCKER ENV
WUD_TRIGGER_MQTT_MOSQUITTO_URL=mqtt://IP:1883
WUD_TRIGGER_MQTT_MOSQUITTO_HASS_ENABLED=true
WUD_TRIGGER_MQTT_MOSQUITTO_HASS_DISCOVERY=true
WUD_WATCHER_LOCAL_CRON=0 0,6,12,18 * * *
WUD_REGISTRY_HUB_PUBLIC_AUTH=BASE64ENCODED (USER:ACCESSTOKEN)
WUD_AUTH_OIDC_POCKET-ID_CLIENTID=XXX
WUD_AUTH_OIDC_POCKET-ID_CLIENTSECRET=XXX
WUD_AUTH_OIDC_POCKET-ID_DISCOVERY=https://my.fqdn/.well-known/openid-configuration
WUD_AUTH_OIDC_POCKET-ID_REDIRECT=true
```

https://getwud.github.io/wud/#/configuration/registries/hub/ - taking information from here WUD_REGISTRY_HUB_PUBLIC_AUTH is a valid environment variable so im confused why PUBLIC is not allowed.
