### ISSUE TITLE
Docker Compose Trigger Fails on Some Containers

### ISSUE THREAD

**Issue by jrbarronumd** [getwud/wud#581]
I recently started using the Docker Compose trigger, in manual mode.  For certain containers, it works perfectly - compose file is updated, and the container is updated.  For the rest, nothing happens, and the log produces a single line, shown below.  I can't seem to figure out any similarities between the failures, or the successes.  Mostly all from the GHCR.  It seems consistent though.  When I recreate a successfully updated container at an older version, and recreate the WUD container (or not), it works to update that container every time.  But it has never failed on one, and succeeded in a later attempt.

`WARN whats-up-docker/container: Error when running trigger (type=dockercompose, name=local) (Cannot read properties of undefined (reading 'includes'))`

WUD environment variables below:

```
environment:
      - TZ=$TZ
      - WUD_LOG_LEVEL=trace
      - WUD_WATCHER_jb-server_WATCHBYDEFAULT=false 
      - WUD_REGISTRY_HUB_PUBLIC_TOKEN=$HUB_TOKEN
      - WUD_WATCHER_jb-server_SOCKET=/var/run/docker.sock
      - WUD_WATCHER_jb-server_CRON=0 1 * * *
      - WUD_WATCHER_server-002_HOST=10.0.0.2
      - WUD_WATCHER_server-002_CRON=0 1 * * *
      - WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_FILE=/wud/docker-compose.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_BACKUP=true
      - WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_PRUNE=true
      - WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_AUTO=false
      - WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_MODE=simple
```

Love this project, thank you for sharing your work!!

**Comment by setrin** [comment]
@jrbarronumd Do you mind sharing Docker-Compose file with containers that fails for you?

**Comment by jrbarronumd** [comment]
Gladly.  It a massive file, so I'll share a couple containers that worked for updating, and a couple that did not.  Audiobookshelf and unifi worked, and dbbackups and LLDAP did not.

Thanks!

```
 ######################################### What's Up Docker?
  # https://getwud.github.io/wud/#/
  whatsupdocker:
    container_name: wud
    image: ghcr.io/getwud/wud:8.0.1
    restart: unless-stopped
    networks:
      t2_proxy:
        ipv4_address: 10.0.200.14
      local_net:
        ipv4_address: 172.20.0.14
    ports:
      - "3014:3000"
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: curl --fail http://localhost:${WUD_SERVER_PORT:-3000}/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERDIR/whats-up-docker:/store
      - $DOCKERDIR/docker-compose.yml:/wud/docker-compose.yml
    environment:
      - TZ=$TZ
      - WUD_LOG_LEVEL=trace
      - WUD_WATCHER_jb-server_WATCHBYDEFAULT=false
      - WUD_REGISTRY_HUB_PUBLIC_TOKEN=$HUB_TOKEN
      - WUD_WATCHER_jb-server_SOCKET=/var/run/docker.sock
      - WUD_WATCHER_jb-server_CRON=0 1 * * *
      - WUD_WATCHER_server-002_HOST=10.0.0.2
      - WUD_WATCHER_server-002_CRON=0 1 * * *
      - WUD_TRIGGER_MQTT_MOSQUITTO_URL=mqtt://172.20.0.7:1883
      - WUD_TRIGGER_MQTT_MOSQUITTO_USER=mqttuser
      - WUD_TRIGGER_MQTT_MOSQUITTO_PASSWORD=$MQTT_PW
      - WUD_TRIGGER_MQTT_MOSQUITTO_HASS_ENABLED=true
      - WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_FILE=/wud/docker-compose.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_BACKUP=true
      - WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_PRUNE=true
      - WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_AUTO=false
      - WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_MODE=simple
    labels:
      - wud.watch=true
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - wud.link.template=https://github.com/fmartinou/whats-up-docker/releases/tag/$${major}.$${minor}.$${patch}
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.wud-rtr.entrypoints=https"
      - "traefik.http.routers.wud-rtr.rule=Host(`wud.$DOMAINNAME`)"
      - "traefik.http.routers.wud-rtr.tls=true"
      ## HTTP Services
      - "traefik.http.routers.wud-rtr.service=wud-svc"
      - "traefik.http.services.wud-svc.loadbalancer.server.port=3000"
      ## Middlewares
      - "traefik.http.routers.wud-rtr.middlewares=chain-authelia@file"

 ######################################### AudiobookShelf - Audiobook server
  # https://github.com/advplyr/audiobookshelf
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.18.1
    container_name: audiobookshelf
    restart: unless-stopped
    networks:
      local_net:
        ipv4_address: 172.20.0.46
    ports:
      - "8246:80"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $PLEXDIR/Audiobooks:/audiobooks:ro
      - $PLEXDIR/Podcasts:/podcasts
      - $PLEXDIR/Podcasts_Other:/podcasts_other
      - $DOCKERDIR/audiobookshelf/metadata:/metadata
      - $DOCKERDIR/audiobookshelf/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      AUDIOBOOKSHELF_UID: $PUID
      AUDIOBOOKSHELF_GID: $PGID
    labels:
      - wud.watch=true
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - wud.link.template=https://github.com/advplyr/audiobookshelf/releases/tag/v$${major}.$${minor}.$${patch}

 ######################################### Unifi Controller
  # https://hub.docker.com/r/jacobalberty/unifi
  unifi-controller:
    container_name: unifi
    image: ghcr.io/jacobalberty/unifi-docker:v9.0.108
    restart: always
    networks:
      local_net:
        ipv4_address: 172.20.0.12
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/unifi:/unifi
      - $DOCKERDIR/shared:/shared
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"
      - "8443:8443"
      - "8843:8843"
      - "8880:80"
      - "6789:6789" # For mobile throughput test on LinuxServer container
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - wud.watch=true
      - wud.tag.include=^v\d+\.\d+\.\d+$$
      - wud.link.template=https://community.ui.com/releases/r/network/$${major}.$${minor}.$${patch}

 ######################################### LLDAP
  # https://github.com/lldap/lldap
  lldap:
    image: ghcr.io/lldap/lldap:2025-01-20
    container_name: lldap
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      t2_proxy:
        ipv4_address: 10.0.200.92
      local_net:
        ipv4_address: 172.20.0.92
    volumes:
      - $DOCKERDIR/lldap:/data
    environment:
      - UID=$PUID
      - GID=$PGID
      - TZ=$TZ
      - LLDAP_JWT_SECRET=$LLDAP_JWT_SECRET
      - LLDAP_KEY_SEED=$LLDAP_KEY_SEED
      - LLDAP_LDAP_BASE_DN=dc=$MY_DOMAIN,dc=us
    labels:
      - wud.watch=true
      - wud.tag.include=^\d+\-\d+\-\d+$$
      - wud.link.template=https://github.com/lldap/lldap/releases
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.lldap-rtr.entrypoints=https"
      - "traefik.http.routers.lldap-rtr.rule=Host(`lldap.$DOMAINNAME`)"
      - "traefik.http.routers.lldap-rtr.tls=true"
      ## HTTP Services
      - "traefik.http.routers.lldap-rtr.service=lldap-svc"
      - "traefik.http.services.lldap-svc.loadbalancer.server.port=17170"
      ## Middlewares
      - "traefik.http.routers.lldap-rtr.middlewares=chain-no-auth@file"

 ######################################### tiredofit/docker-db-backup - docker db backup manager
  # https://github.com/tiredofit/docker-db-backup
  dbbackups:
    image: ghcr.io/tiredofit/docker-db-backup:4.1.12
    container_name: dbbackups
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    secrets:
      - auth_db_pw
      - wp_db_pw
      - influx_admin_token
    depends_on:
      - db_recipes
    networks:
      local_net:
        ipv4_address: 172.20.0.101
    links:
      - db_recipes
    volumes:
      - $DOCKERDIR/db_backups/backups:/backup
      - $DOCKERDIR/db_backups/pre-scripts:/assets/scripts/pre
      - $DOCKERDIR/db_backups/post-scripts:/assets/scripts/post
      - $DOCKERDIR/db_backups/logs:/logs
      - $DOCKERDIR/db_backups/notifications:/notifications
    env_file:
      - $DOCKERDIR/db_backups/.env # Job-specific env variables in this file (except ones below shared by other containers, below)
    environment:
      - TIMEZONE=$TZ
      - USER_DBBACKUP=$PUID
      - GROUP_DBBACKUP=$PGID
      - DEFAULT_SKIP_AVAILABILITY_CHECK=TRUE
      # Authelia
      - DB01_USER=$AUTH_DB_USER
      - DB01_PASS_FILE=/run/secrets/auth_db_pw
      # Wordpress
      - DB02_USER=$WP_DB_USER
      - DB02_PASS_FILE=/run/secrets/wp_db_pw
      # Tandoor Recipes (Postgres)
      - DB03_PASS=$POSTGRES_PASSWORD
      # InfluxDB
      - DB04_PASS_FILE=/run/secrets/influx_admin_token
    labels:
      - wud.watch=true
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - wud.link.template=https://github.com/tiredofit/docker-db-backup/releases/tag/$${major}.$${minor}.$${patch}
```
