### ISSUE TITLE
Healthcheck does not work with 'wget'

### ISSUE THREAD

**Issue by ushandelucca** [getwud/wud#592]
If WUD is used with Docker Compose, a health check can be performed. An example is given in the documentation. In this example, the 'wget' command is used. However, this command is not included in version 8.0.1. See the incorrect [documentation](https://getwud.github.io/wud/#/configuration/?id=complete-example).

A possible solution would be to use the existing 'curl' command instead of 'wget'. 
```   
...
healthcheck:
  test: curl -sSf http://localhost:3000 > /dev/null
  interval: 10s
  timeout: 10s
  retries: 3
  start_period: 10s       
...
```

**Comment by fmartinou** [comment]
Hi,

The documentation regarding healthcheck is up-to-date here:
https://getwud.github.io/wud/#/monitoring/?id=example

```yaml
services:

  whatsupdocker:
    image: getwud/wud:7.2.0
    ...
    healthcheck:
      test: curl --fail http://localhost:${WUD_SERVER_PORT:-3000}/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
```

But I forgot to change the example you point out; I'll fix it.
