### ISSUE TITLE
What's the correct config for the Docker Compose trigger?

### ISSUE THREAD

**Issue by Nelluk** [getwud/wud#598]
I've been trying to get the Docker-Compose trigger to work to update a project's compose file automatically. Here is my WUD config:

```yaml
version: '3'

services:
  whatsupdocker:
    image: fmartinou/whats-up-docker
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/docker/docker_compose_projects:/docker_compose_projects
    ports:
      - 3000:3000
    environment:
      - TZ=America/Detroit
      - WUD_LOG_LEVEL=debug
      - WUD_REGISTRY_LSCR_USERNAME=my@email.com
      - WUD_REGISTRY_LSCR_TOKEN=key

      - WUD_TRIGGER_SMTP_APPRISE1_SIMPLETITLE=WUD Update - container $${name} can be updated
      - WUD_TRIGGER_APPRISE_APPRISE1_URL=http://192.168.1.244:8000
      - WUD_TRIGGER_APPRISE_APPRISE1_URLS=apprise://192.168.1.244:8000/key/?tags=mail
      - WUD_TRIGGER_APPRISE_APPRISE1_ONCE=false
      - WUD_TRIGGER_APPRISE_APPRISE1_MODE=batch

      - WUD_TRIGGER_DOCKERCOMPOSE_MAINTAINERR_THRESHOLD=minor
      - WUD_TRIGGER_DOCKERCOMPOSE_MAINTAINERR_BACKUP=true
      - WUD-TRIGGER_DOCKERCOMPOSE_MAINTAINERR_FILE=/docker_compose_projects/maintainerr/docker-compose.yml
      - WUD-TRIGGER_DOCKERCOMPOSE_MAINTAINERR_AUTO=true

      - WUD_WATCHER_LOCAL_CRON=0 */12 * * *

```

Is this the right idea? Do I need to have a unique trigger for each project I want to have updated? I thought this config would work at least for one project ('maintainerr') but I do not see anything in the logs and this trigger does not show up in the WUD UI.

My maintainerr docker-compose.yml is simply this:

```yaml
services:
    maintainerr:
        image: ghcr.io/jorenn92/maintainerr:2.8.0 
        ports:
          - 6246:6246 
        labels:
          - 'wud.tag.include=^\d+\.\d+\.\d+$$'
          - 'wud.link.template=https://github.com/jorenn92/Maintainerr/releases/tag/v$${major}.$${minor}.$${patch}'

```
