### ISSUE TITLE
WUD won't work with docker-socket-proxy

### ISSUE THREAD

**Issue by L0sWach0s** [getwud/wud#627]
I try to use the docker-socket-proxy with WUD. I configured as told, but WUP can't get access to the docker socket, it always tries to connect to the localhost.

**Error message:** 
Error when trying to get the list of the containers to watch (connect **ECONNREFUSED 127.0.0.1:80**)

When I'm inside the container, I can access to the docker socket by using the curl command.

Attached my docker compose file:

```
services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - ./store:/store
#      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - WUD_WATCHER_DOCKER_HOST=tcp://docker-socket-proxy:2375
      - WUD_TRIGGER_LOG_LEVEL=info
      - WUD_WATCHER_DOCKER_PORT=2375
      - WUD_WATCHER_DOCKER_WATCHALL=true
      - WUD_LOG_LEVEL=debug

    networks:
      - socket

    healthcheck:
      test: curl --fail http://localhost:${WUD_SERVER_PORT:-3000}/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s 

networks:
  socket:
    name: docker-socket-proxy
    external: true

```

Log Message:

```
wud  | 09:54:23.417  INFO whats-up-docker/watcher.docker.docker: Register with configuration {"watchall":true,"port":2375,"host":"tcp://docker-socket-proxy:2375","socket":"/var/run/docker.sock","cron":"0 * * * *","watchbydefault":true,"watchevents":true,"watchatstart":true}
wud  | 09:54:23.418  INFO whats-up-docker/watcher.docker.docker: Cron scheduled (0 * * * *)
wud  | 09:54:23.422  INFO whats-up-docker/registry: No authentication configured => Allow anonymous access
wud  | 09:54:23.424  INFO whats-up-docker/authentication.anonymous.anonymous: Register with configuration {}
wud  | 09:54:23.424 DEBUG whats-up-docker/api: API/UI enabled => Start Http listener on port 3000
wud  | 09:54:23.429  WARN whats-up-docker: Anonymous authentication is enabled; please make sure that the app is not exposed to unsecure networks
wud  | (node:7) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
wud  | (Use `node --trace-deprecation ...` to show where the warning was created)
wud  | 09:54:23.433  INFO whats-up-docker/api: Server listening on port 3000 (HTTP)
wud  | 09:54:24.422  INFO whats-up-docker/watcher.docker.docker: Cron started (0 * * * *)
wud  | 09:54:24.433  INFO whats-up-docker/watcher.docker.docker: Listening to docker events
wud  | 09:54:24.437  WARN whats-up-docker/watcher.docker.docker: Error when trying to get the list of the containers to watch (connect ECONNREFUSED 127.0.0.1:80)
wud  | 09:54:24.437  INFO whats-up-docker/watcher.docker.docker: Cron finished (0 containers watched, 0 errors, 0 available updates)
wud  | 09:54:24.437  WARN whats-up-docker/watcher.docker.docker: Unable to listen to Docker events [connect ECONNREFUSED 127.0.0.1:80]
wud  | 09:54:24.437 DEBUG whats-up-docker/watcher.docker.docker: connect ECONNREFUSED 127.0.0.1:80 (err.code=ECONNREFUSED)
wud  |     Error: connect ECONNREFUSED 127.0.0.1:80
wud  |         at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1634:16)
wud  | 10:00:00.494  INFO whats-up-docker/watcher.docker.docker: Cron started (0 * * * *)
wud  | 10:00:00.496  WARN whats-up-docker/watcher.docker.docker: Error when trying to get the list of the containers to watch (connect ECONNREFUSED 127.0.0.1:80)
wud  | 10:00:00.496  INFO whats-up-docker/watcher.docker.docker: Cron finished (0 containers watched, 0 errors, 0 available updates)
```
