### ISSUE TITLE
How to not WATCHATSTART?

### ISSUE THREAD

**Issue by Fayyaadh** [getwud/wud#637]
Hi there

New to wud, so have a small question.

How do I get it so that wud does NOT check for containers at startup of the wud container?

I know the documentation says that `WUD_WATCHER_{watcher_name}_WATCHATSTART` is deprecated and the default value is `true if store is empty`.

But I don't know what this means exactly.

Thanks

**Comment by j10k** [comment]
Your research already got you half of the way: you can mount a volume at `/store` in the container, which allows WUD to remember when it has last checked for updates on container restart. I used a docker-managed volume (rather than a bind mount) for this. Excerpt from my `docker-compose.yml`:

```
services:
  whatsupdocker:
# lines removed for brevity
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # while the content is not that important, persistent storage prevents refreshing container status
      # from registries, possibly running into quotas in a restart loop or during testing
      - whatsupdocker:/store
# lines removed for brevity

volumes:
  whatsupdocker:

```

This is partially documented at [WUD Storage](https://getwud.github.io/wud/#/configuration/storage/)
