### ISSUE TITLE
docker compose trigger not editing compose files

### ISSUE THREAD

**Issue by upendedshark** [getwud/wud#642]
Hi,

Based on the documentation, I thought docker compose triggers would also update the compose files, and WUD_TRIGGER_DOCKERCOMPOSE_{trigger_name}_BACKUP would create a backup.

using the trigger is successfully updating the container, but the compose file remains unchanged and I can't find the backup file anywhere.

Am I configuring this properly?

```
services:
  whatsupdocker:
    image: getwud/wud:8.0.0
    container_name: wud
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/datadisk/data/appdata/wud:/store
      - /srv/datadisk/data/docker/compose/monitoring/docker-compose.yml:/compose/monitoring.yml
      - /srv/datadisk/data/docker/compose/plex/docker-compose.yml:/compose/plex.yml
    ports:
      - 3000:3000
    environment:
      - PUID=1001
      - PUID=100
      - TZ=Asia/Bangkok
     # Monitoring Stack
      - WUD_TRIGGER_DOCKERCOMPOSE_MONITORING_FILE=/compose/monitoring.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_MONITORING_BACKUP=true
      - WUD_TRIGGER_DOCKERCOMPOSE_MONITORING_PRUNE=true
      - WUD_TRIGGER_DOCKERCOMPOSE_MONITORING_AUTO=false
      # Plex Stack
      - WUD_TRIGGER_DOCKERCOMPOSE_PLEX_FILE=/compose/plex.yml
      - WUD_TRIGGER_DOCKERCOMPOSE_PLEX_BACKUP=true
      - WUD_TRIGGER_DOCKERCOMPOSE_PLEX_PRUNE=true
      - WUD_TRIGGER_DOCKERCOMPOSE_PLEX_AUTO=false
    networks:
      - frontend_wud
    labels:
      - 'wud.watch=true'
      - 'wud.tag.include=^\d{1,2}\.\d+\.\d+$$'
      - 'wud.link.template=https://github.com/getwud/wud/releases/tag/$${major}.$${minor}.$${patch}'
      - 'wud.trigger.include=dockercompose.wud'
networks:
  frontend_wud:
    external: true
```

**Comment by BoskiAlvaro** [comment]
I have the same problem. It looks like docker-compose file was updated inside container but it's not reflected in mounted file. Also I noticed, that when I changed something in docker-compose file on host (for example change ghcr.io/yourls/yourls:1.10.3 to 1.10.4), and I logged to wud contained and i do something like that "cat /wud/docker-compose.yml | grep ghcr.io/yourls/yourls", the output is still ghcr.io/yourls/yourls:1.10.3...

my wud configuration:

```
  wud:
    container_name: wud
    restart: unless-stopped
    image: ghcr.io/getwud/wud:8.2.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/docker-compose.yml:/wud/docker-compose.yml
      - ${USERDIR}/docker/docker-compose.yml.back:/wud/docker-compose.yml.back
    ports:
       - "3000:3000"
    environment:
      TZ: ${TZ}
      WUD_LOG_LEVEL: "info"
      WUD_TRIGGER_DOCKER_LOCAL_AUTO: "false"
      WUD_TRIGGER_DOCKER_LOCAL_MODE: "simple"
      WUD_WATCHER_LOCAL_CRON: "0 1 * * *"
      WUD_WATCHER_LOCAL_JITTER: "120000"
      WUD_WATCHER_LOCAL_WATCHBYDEFAULT: "true"
      WUD_REGISTRY_HUB_PUBLIC_LOGIN: ${WUD_DOCKER_HUB_LOGIN}
      WUD_REGISTRY_HUB_PUBLIC_PASSWORD: ${WUD_DOCKER_HUB_PASSWORD}
      WUD_REGISTRY_GHCR_PRIVATE_USERNAME: ${WUD_GITHUB_LOGIN}
      WUD_REGISTRY_GHCR_PRIVATE_TOKEN: ${WUD_GITHUB_TOKEN}
      WUD_REGISTRY_LSCR_PRIVATE_USERNAME: ${WUD_GITHUB_LOGIN}
      WUD_REGISTRY_LSCR_PRIVATE_TOKEN: ${WUD_GITHUB_TOKEN}
      WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_AUTO: "false"
      WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_FILE: "/wud/docker-compose.yml"
      WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_BACKUP: "true"
      WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_PRUNE: "true"
      WUD_TRIGGER_DOCKERCOMPOSE_LOCAL_DRYRUN: "false"
```

What I'm doing wrong?
