### ISSUE TITLE
Watch digest not working

### ISSUE THREAD

**Issue by NChief** [getwud/wud#644]
I have container running postgresql:
```yml
---
services:
  db:
    image: 'postgres:15'
    labels:
      - wud.tag.include=^\d+$$
      - wud.watch.digest=true
```

But wud keeps saying that there is an update to 17 available. I do not want 17. But I do want to know if the digest on the 15 tag has changed.

Am I misunderstanding something? This is taken more or less straight from the [documentation](https://getwud.github.io/wud/#/configuration/watchers/?id=enable-digest-watching).
