### ISSUE TITLE
Running WUD in rootless mode

### ISSUE THREAD

**Issue by matteo-martinelli** [getwud/wud#662]
I am trying to run WUD id rootless mode. In the following there is the compose I am using: 

```
services:
  whatsupdocker:
    image: fmartinou/whats-up-docker:6.6.1 
    container_name: Whats-Up-Docker
    restart: unless-stopped
    user: "1000:1000"
    networks: 
      - docker-tools-bridge
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /wud-data:/store  
    environment:
      - WUD_WATCHER_LOCAL_WATCHBYDEFAULT=false
      - WUD_WATCHER_LOCAL_CRON=0 6 * * *
      - WUD_AUTH_BASIC_WMEX_USER=${WUD_USR}
      - WUD_AUTH_BASIC_WMEX_HASH=${WUD_PW}
      - WUD_TRIGGER_TELEGRAM_MEXTELEBOT_BOTTOKEN=${TELEGRAM_BOT_TOKEN}
      - WUD_TRIGGER_TELEGRAM_MEXTELEBOT_CHATID=${TELEGRAM_CHATID}
```
I am using a .env file mapped on the user and group `1000:1000` with permissions to be read by the user and group members. 
Nevertheless, running `docker compose up -d`, the message `open /path/to/.env: permission denied`. 

So, I am wondering... Can WUD be deployed in rootless mode?

**Comment by cryptogeek13** [comment]
I have WUD running under a non-root user inside the container without any problems. But there might be a misconception: 
[Setting `user` in docker-compose.yml](https://github.com/compose-spec/compose-spec/blob/main/schema/compose-spec.json) to anything non-root is **not the same** as [running docker rootless](https://docs.docker.com/engine/security/rootless/). It will only start the application process inside of the container with another user, docker itself will still run as a root process and so will any container.

That misconception might be related to your problem, because to run an app inside of a container with another user setting `user`, you only need to make sure the permissions on any volume or mount is correct so the application does have access at runtime.
You do **not** need to set those permissions on your .env-file. In fact, `.env` **has to be readable** by the user that is starting the container, so **your user** you are executing `docker compose up -d` with.

**Comment by garettmd** [comment]
I've tried running wud in rootless mode (actually running it under my user uid of 1000 rather than root). I'm passing in the user socket to wud via the env var `WUD_WATCHER_user_SOCKET=/run/user/1000/docker.sock`, but I get an ENOENT error from wud. I'm pretty sure that's the correct socket to use:

```shell
$ ls -l /run/user/1000/docker.sock
srw-rw---T 1 ubuntu 100989 0 Aug  8 14:47 /run/user/1000/docker.sock
```

Is there something I'm doing wrong?

**Comment by proud-nerd** [comment]
> I've tried running wud in rootless mode (actually running it under my user uid of 1000 rather than root). I'm passing in the user socket to wud via the env var `WUD_WATCHER_user_SOCKET=/run/user/1000/docker.sock`, but I get an ENOENT error from wud. I'm pretty sure that's the correct socket to use:
> 
> $ ls -l /run/user/1000/docker.sock
> srw-rw---T 1 ubuntu 100989 0 Aug  8 14:47 /run/user/1000/docker.sock
> 
> Is there something I'm doing wrong?

I think this is also a misconception about what is _inside_ of the container and what is _on the host_. If you set `WUD_WATCHER_user_SOCKET=/run/user/1000/docker.sock`, you tell the container to connect to `/run/user/1000/docker.sock` _inside_ of the container and I'm pretty sure, that socket does not exist, it only exists on your host.
It should work, if you also mount your user socket into the container:

```
volumes:
      - /run/user/1000/docker.sock:/run/user/1000/docker.sock
```

Note, that using :ro on a socket does not do what you'd expect, since anyone who has access to the socket has full access to the docker daemon, with :ro you only can't change _the socket itself_. I'd recommend taking a look at the [Docker Socket Proxy](https://github.com/Tecnativa/docker-socket-proxy), there are plenty of issues how to configure this in this repo.

**Comment by pred2k** [comment]
hi, the thread starter @matteo-martinelli wrote "rootless mode" but his docker compose instruction `user: "1000:1000"` suggests that he wants to run WUD with a non-root user.

This is what i'm also trying with my `compose.yaml`:

```yaml
services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    user: 1000:1000
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file: .env
```

WUD logs this error:
```
WARN whats-up-docker/watcher.docker.local: Error when trying to get the list of the containers to watch (connect EACCES /var/run/docker.sock)
wud  | 19:01:58.985  WARN whats-up-docker/watcher.docker.local: Unable to listen to Docker events [connect EACCES /var/run/docker.sock]
```

I can run other containers with non-root and access to `/var/run/docker.sock` on my host, like [tinyauth](https://github.com/steveiliop56/tinyauth).

**Does any1 has an idea how to harden the WUD container runtime?** Maybe also even with `read_only: true` because i don't see a reason why there should be any write action in the root volume.
