### ISSUE TITLE
Unsupported Registry lscr.linux

### ISSUE THREAD

**Issue by LukeBurke99** [getwud/wud#673]
I know similar issues have been raised but I was unable to find one that was exactly what I am experiencing. Here it the logs for this message:

> 20:51:00.777  WARN whats-up-docker/watcher.docker.blackflag: Error when processing (Unsupported Registry lscr.linux) (container=blackflag_qbittorrent)

> 20:51:00.777 DEBUG whats-up-docker/watcher.docker.blackflag: Unsupported Registry lscr.linux (container=blackflag_qbittorrent)
    Error: Unsupported Registry lscr.linux
        at getRegistry (/home/node/app/watchers/providers/docker/Docker.js:138:15)
        at Docker.findNewVersion (/home/node/app/watchers/providers/docker/Docker.js:581:34)
        at Docker.watchContainer (/home/node/app/watchers/providers/docker/Docker.js:496:53)
        at /home/node/app/watchers/providers/docker/Docker.js:465:52
        at Array.map (<anonymous>)
        at Docker.watch (/home/node/app/watchers/providers/docker/Docker.js:465:28)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async Docker.watchFromCron (/home/node/app/watchers/providers/docker/Docker.js:425:34)

> 20:51:00.778  WARN whats-up-docker/watcher.docker.blackflag: Error when processing some containers (Cannot read properties of undefined (reading 'tag'))

> 20:51:00.778  INFO whats-up-docker/watcher.docker.blackflag: Cron finished (0 containers watched, 0 errors, 0 available updates)

And my docker compose is here:

```
whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - /docker/wud/store:/store
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3690:3000
    environment:
      - WUD_LOG_LEVEL=debug
      - TZ=Europe/London
      - WUD_PUBLIC_URL=http://192.168.0.112:3690
      - WUD_AUTH_OIDC_KC_DISCOVERY=https://.../.well-known/openid-configuration
      - WUD_AUTH_OIDC_KC_CLIENTID=wud
      - WUD_AUTH_OIDC_KC_CLIENTSECRET=...
      - WUD_AUTH_OIDC_KC_REDIRECT=true
      # New Registries
      - WUD_REGISTRY_LSCR_PUBLIC_USERNAME=...
      - WUD_REGISTRY_LSCR_PUBLIC_TOKEN=...
      # Local Docker Instance
      - WUD_WATCHER_LOCAL_CRON=51 * * * *
      - WUD_WATCHER_LOCAL_SOCKET=/var/run/docker.sock
      - WUD_WATCHER_LOCAL_WATCHALL=false
      - WUD_WATCHER_LOCAL_WATCHBYDEFAULT=false
      # App Docker Instance
      - WUD_WATCHER_APPS_HOST=192.168.0.11
      - WUD_WATCHER_APPS_CRON=51 * * * *
      - WUD_WATCHER_APPS_WATCHALL=false
      - WUD_WATCHER_APPS_WATCHBYDEFAULT=false
      # Black Flag Docker Instance
      - WUD_WATCHER_BLACKFLAG_HOST=192.168.0.102
      - WUD_WATCHER_BLACKFLAG_CRON=51 * * * *
      - WUD_WATCHER_BLACKFLAG_WATCHALL=false
      - WUD_WATCHER_BLACKFLAG_WATCHBYDEFAULT=false
    labels:
      - wud.watch=true
      - wud.watch.digest=true
``` 

I can see from portainer that there is a new release available for qBittorrent but the LSCR doesn't seem to be picking it up. I followed the tutorial exactly and gave the token the correct permissions.

Let me know if you need to see anything else to help you investigate.

The qBittorrent compose looks like this btw:
```
qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
```
