### ISSUE TITLE
Getting multiple mails and weird times

### ISSUE THREAD

**Issue by TheGor1lla** [getwud/wud#687]
I have multiple containers managed in docker compose files that I watch with WUD. Most of them have custom tag rules:  

```
  nginx_recipes:
    image: nginx:1.27.4
    labels:
      - ${WUD_SEMVER_WATCHER} #wud.tag.include=^\d+\.\d+\.\d+$$
```
  
My WUD config:  

```
  whatsupdocker:
    image: getwud/wud:8.0.1
    labels:
      - ${WUD_SEMVER_WATCHER}
    expose:
      - 3000
    environment:
      - TZ=Europe/Berlin
      - WUD_TRIGGER_SMTP_MAIL_MODE=batch
      - WUD_TRIGGER_SMTP_MAIL_ONCE=false
      - WUD_TRIGGER_SMTP_MAIL_HOST=${EMAIL_HOST}
      - WUD_TRIGGER_SMTP_MAIL_PORT=${EMAIL_PORT}
      - WUD_TRIGGER_SMTP_MAIL_USER=${EMAIL_HOST_USER}
      - WUD_TRIGGER_SMTP_MAIL_PASS=${EMAIL_HOST_PASSWORD}
      - WUD_TRIGGER_SMTP_MAIL_FROM=whatsupdocker@${DOMAIN}
      - WUD_TRIGGER_SMTP_MAIL_TO=${EMAIL_HOST_USER}
      - WUD_TRIGGER_SMTP_MAIL_TLS_ENABLED=false
      - WUD_WATCHER_LOCAL_CRON=0 1 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${VOLUMES_ROOT_PATH}/wud:/store
    networks:
```

I expected to get a mail everyday at 1 o'clock with all available updates, e.g. "19 new containers available".  
I currently get 2 identical mails when I restart the container and like 2 identical mails every 30min-1hr. Sometimes even more than 2. 
My mail stacks works as intended for every other application, so I guess there is some problem with my WUD configuration.
